import { assertPolicyReadyToCompile } from "../policy-ir/state.js";
import type { PolicyIR, Predicate, Scalar } from "../policy-ir/types.js";
import { parsePolicyIR } from "../policy-ir/validate.js";
import type {
  CompilerManifest,
  CompilerRuleMapping,
  RegoCompilationResult,
} from "./types.js";

class LineWriter {
  readonly lines: string[] = [];

  get nextLine(): number {
    return this.lines.length + 1;
  }

  add(...lines: string[]): void {
    this.lines.push(...lines);
  }
}

function scalarLiteral(value: Scalar): string {
  return JSON.stringify(value);
}

function comparisonOperator(operator: string): string {
  const operators: Record<string, string> = {
    eq: "==",
    neq: "!=",
    lt: "<",
    lte: "<=",
    gt: ">",
    gte: ">=",
  };
  const compiled = operators[operator];
  if (!compiled) {
    throw new Error(`Unsupported comparison operator after validation: ${operator}`);
  }
  return compiled;
}

function emitBooleanRule(writer: LineWriter, name: string, bodyLines: readonly string[]): void {
  writer.add(`${name} if {`, ...bodyLines.map((line) => `  ${line}`), "}", "");
}

function emitPredicate(writer: LineWriter, predicate: Predicate, name: string): void {
  if (predicate.type === "compare") {
    emitBooleanRule(writer, name, [
      `input.${predicate.field} ${comparisonOperator(predicate.operator)} ${scalarLiteral(predicate.value)}`,
    ]);
    return;
  }

  if (predicate.type === "in") {
    const values = [...predicate.values]
      .map((value) => scalarLiteral(value))
      .sort()
      .join(", ");
    emitBooleanRule(writer, name, [`input.${predicate.field} in {${values}}`]);
    return;
  }

  if (predicate.type === "not") {
    const childName = `${name}_0`;
    emitPredicate(writer, predicate.child, childName);
    emitBooleanRule(writer, name, [`not ${childName}`]);
    return;
  }

  const childNames = predicate.children.map((child, index) => {
    const childName = `${name}_${index}`;
    emitPredicate(writer, child, childName);
    return childName;
  });
  if (predicate.type === "and") {
    emitBooleanRule(writer, name, childNames);
    return;
  }
  for (const childName of childNames) {
    emitBooleanRule(writer, name, [childName]);
  }
}

function emitInputValidation(writer: LineWriter): { startLine: number; endLine: number } {
  const startLine = writer.nextLine;
  emitBooleanRule(writer, "valid_input", [
    "is_object(input)",
    'object.keys(input) == {"daysSincePurchase", "usageBasisPoints", "promotionalPurchase", "finalSale", "managerApproved", "planType"}',
    "is_number(input.daysSincePurchase)",
    "input.daysSincePurchase >= 0",
    "floor(input.daysSincePurchase) == input.daysSincePurchase",
    "is_number(input.usageBasisPoints)",
    "input.usageBasisPoints >= 0",
    "floor(input.usageBasisPoints) == input.usageBasisPoints",
    "is_boolean(input.promotionalPurchase)",
    "is_boolean(input.finalSale)",
    "is_boolean(input.managerApproved)",
    "is_string(input.planType)",
    'input.planType in {"ANNUAL", "ENTERPRISE", "MONTHLY"}',
  ]);
  return { startLine, endLine: writer.lines.length - 1 };
}

function emitDecisionRule(
  writer: LineWriter,
  policy: PolicyIR,
  predicateRule: string | null,
  excludedPredicateRules: readonly string[],
  decision: "ALLOW" | "DENY" | "REVIEW",
  matchedRuleId: string | null,
  explanation: string,
): { startLine: number; endLine: number } {
  const startLine = writer.nextLine;
  writer.add(
    "decision := {",
    `  "decision": ${JSON.stringify(decision)},`,
    `  "matchedRuleId": ${JSON.stringify(matchedRuleId)},`,
    `  "explanation": ${JSON.stringify(explanation)},`,
    `  "policyVersion": ${policy.version}`,
    "} if {",
    "  valid_input",
    ...excludedPredicateRules.map((name) => `  not ${name}`),
    ...(predicateRule ? [`  ${predicateRule}`] : []),
    "}",
    "",
  );
  return { startLine, endLine: writer.lines.length - 1 };
}

export function compilePolicyToRego(policyValue: unknown): RegoCompilationResult {
  const policy = parsePolicyIR(policyValue);
  assertPolicyReadyToCompile(policy);

  const writer = new LineWriter();
  writer.add(
    "# Generated by PolicyTwin rego-compiler.v1. Do not edit.",
    "package policytwin.refund",
    "",
    "import rego.v1",
    "",
  );
  const inputValidation = emitInputValidation(writer);
  const orderedRules = [...policy.rules].sort(
    (left, right) => right.priority - left.priority || left.id.localeCompare(right.id),
  );
  const predicateRules = orderedRules.map((rule, index) => {
    const name = `rule_${index}_predicate`;
    emitPredicate(writer, rule.when, name);
    return name;
  });

  const ruleMappings: CompilerRuleMapping[] = [];
  orderedRules.forEach((rule, index) => {
    const mapping = emitDecisionRule(
      writer,
      policy,
      predicateRules[index] ?? null,
      predicateRules.slice(0, index),
      rule.decision,
      rule.id,
      rule.explanationTemplate,
    );
    ruleMappings.push({
      ruleId: rule.id,
      priority: rule.priority,
      sourceClauseIds: [...rule.sourceClauseIds],
      predicateRule: predicateRules[index] ?? "",
      ...mapping,
    });
  });

  const defaultMapping = emitDecisionRule(
    writer,
    policy,
    null,
    predicateRules,
    policy.defaultDecision,
    null,
    "No explicit rule matched; applied the accepted default decision.",
  );
  const source = writer.lines.join("\n");
  const manifest: CompilerManifest = {
    schemaVersion: "1",
    compilerVersion: "rego-compiler.v1",
    regoSyntaxVersion: "v1",
    policyId: policy.policyId,
    policyVersion: policy.version,
    packageName: "policytwin.refund",
    query: "data.policytwin.refund.decision",
    inputValidation: {
      mode: "REGO_AND_PREVALIDATED",
      ...inputValidation,
    },
    ruleMappings,
    defaultMapping: {
      decision: policy.defaultDecision,
      ...defaultMapping,
    },
    sourceBytes: new TextEncoder().encode(source).length,
  };
  return { source, manifest };
}
